Run examples with php wasm
php/web-php pull request #1097
Opened 2024-10-16 13:51 UTC by soyuka

Adds a PHP Wasm binary to run documentation examples in the browser.

https://github.com/user-attachments/assets/5a28730d-265a-48dd-8fb8-9e5cea0f0d5b

see also https://github.com/php/doc-en/issues/3259

I've builtin `PHP wasm 8.4.0-dev` and I'm not sure what would be preferred to keep this up to date. If you want to reproduce the build see:

https://github.com/soyuka/php-wasm/pull/7

Clone that branch and execute: 

```
docker buildx bake
cp build/* ../phpdoc/web-php/js
```

2024-10-16 14:04 UTC, soyuka commented
https://github.com/user-attachments/assets/527aaa1d-4ba1-4098-a7e0-3b407e386937

2024-10-16 14:24 UTC, dunglas commented on js/interactive-examples.js
> +	const {ccall} = await phpBinary({
```suggestion
  const {ccall} = await phpBinary({
```

(mixed tabs and spaces)

2024-10-16 14:24 UTC, dunglas commented on js/interactive-examples.js
> +		const phpcode = example.querySelector('.phpcode');
```suggestion
  document.querySelectorAll('.example').forEach((example) => {
    const button = document.createElement('button');
    const phpcode = example.querySelector('.phpcode');
```

2024-10-16 14:24 UTC, dunglas commented on js/interactive-examples.js
> +		button.onclick = function() {
```suggestion
    button.innerText = 'Run code';
    button.onclick = function() {
```

2024-10-16 14:24 UTC, dunglas commented on js/interactive-examples.js
> +	});
```suggestion
    };

    phpcode.parentNode.insertBefore(button, phpcode);
  });
```

2024-10-16 14:24 UTC, dunglas commented on js/interactive-examples.js
> +  return container;
```suggestion
  const container = document.createElement('div');
  container.classList.add('screen', 'example-contents');

  const title = document.createElement('p');
  title.innerText = 'Output: ';
  container.appendChild(title);

  const div = document.createElement('div');
  div.classList.add('examplescode');
  container.appendChild(div);

  const pre = document.createElement('pre');
  pre.classList.add('examplescode');
  pre.innerText = output;
  div.appendChild(pre);

  return container;
```

CS

2024-10-16 15:25 UTC, stof commented on js/interactive-examples.js
> +        lastOutput.parentNode.removeChild(lastOutput)
must simpler: `lastOutput.remove()` (there is no reason to care about unmaintained browsers not supporting the `remove` method when you are adding a feature requiring WebAssembly to work)

2024-10-16 15:25 UTC, stof commented on js/interactive-examples.js
> +		const button = document.createElement('button');
the created button should use the `button` type instead of the default `submit` type, to avoid issues in case this ends up being used in a place being inside a form.

2024-10-16 15:25 UTC, stof commented on js/interactive-examples.js
> +      ccall("phpw_run", null, ["string"], ['?>' + phpcode.innerText]);
should this use `.innerText` or `.textContent` here ? `innerText` is impacted by the styles of the page

2024-10-16 15:25 UTC, stof commented on js/interactive-examples.js
> +		phpcode.parentNode.insertBefore(button, phpcode);
use `phpcode.before()` instead

2024-10-16 15:34 UTC, stof commented
Disabling many extensions as you did in https://github.com/soyuka/php-wasm/pull/7 is likely to make many examples non working though (in your build, even JSON functions are not available)

2024-10-16 17:17 UTC, soyuka commented on js/interactive-examples.js
> +      ccall("phpw_run", null, ["string"], ['?>' + phpcode.innerText]);
no idea 🤷

2024-10-16 17:20 UTC, soyuka commented
> Disabling many extensions as you did in https://github.com/soyuka/php-wasm/pull/7 is likely to make many examples non working though (in your build, even JSON functions are not available)

Definitely, there are a few things to discuss, I can enable most extensions, some will require additional libraries (for example dom or xml require libxml) and it'll add weight to the build (now it's "only" 3.6 MB).

2024-10-16 17:22 UTC, soyuka commented on include/footer.inc
> +?>
maybe that this deserves only one line?

2024-10-16 19:00 UTC, pronskiy commented on js/interactive-examples.js
> +    const code = phpcode.querySelector('pre code')
```suggestion
    const code = phpcode.querySelector('code')
```

I think `pre` is not needed here, is it?

On the preview site https://web-php-pr-1097.preview.thephp.foundation/manual/en/function.var-dump.php
I see the following error in the console:
![image](https://github.com/user-attachments/assets/238c25a4-530e-4782-85e4-a3cadff1cd61)

2024-10-16 19:01 UTC, pronskiy commented
As I understand, php binary is always loaded now, right? If yes, does it make sense to load it only when the user clicks "Run" for the first time?

2024-10-17 08:58 UTC, soyuka commented on js/interactive-examples.js
> +    const code = phpcode.querySelector('pre code')
weird I have a different HTML on the local version but it works

2024-10-17 08:58 UTC, soyuka commented
done

2024-10-17 14:48 UTC, soyuka commented
Note that we should use brotli or gzip though, I'm unfamiliar with the server architecture behind the php docs website, should I add this directly to the cached.php file?

2024-10-17 16:04 UTC, Girgias commented
@derickr is likely the person that would know this.

2024-10-17 17:34 UTC, jimwins commented
It looks like php.net isn't particularly well set-up for encoding content. You can see how CSS/JS/etc is served up by the `cached.php` file, and testing with `curl --compressed -I` shows that it doesn't get encoded. HTML content does get gzip-encoded, at least.

I'm not sure how much of the encoding happens on our server vs. what Myra does on the edge, but there's probably room for improvement there even outside of encoding the WASM bundle appropriately. The current web configuration isn't in the systems repo yet, though.

2024-10-18 08:58 UTC, lwlwilliam commented
If the modified code can still be highlighted, that would be even better

2024-10-18 09:21 UTC, stof commented
@lwlwilliam this would require bringing an actual code editor (Codemirror or Monaco) instead of just using `contenteditable`

2024-10-21 09:39 UTC, pronskiy commented
@lwlwilliam, @stof, it makes sense for sure, but perhaps as step two in a separate PR? Just to keep this one smaller and delivered sooner. I'm pretty sure some unforeseen bugs will be discovered when this is deployed, and it'll be easier to fix them with smaller steps.

2024-10-21 09:43 UTC, pronskiy commented
@soyuka, what do you think about adding the PHP version in the output label? 
<img width="644" alt="Screenshot 2024-10-21 at 11 42 10 AM" src="https://github.com/user-attachments/assets/6820b2d7-775a-4dc7-9f7a-2bda49aca2ba">

2024-10-21 10:07 UTC, derickr commented
Myra already caches `cached.php` with a 2 minute TTL (and 1 minute in case of a 404), but there are no settings for specific compressions:

```
prefix	/cached.php	2 minutes	1 minute
```

I can ask whether they can do on the fly-compression, but I am not sure whether they do.

To answer @jimwins, the config isn't in the systems repo, as nothing on php-web4 has been "php-ified" yet. I think Sascha set it up with nginx in his own way. There is no `/local/systems` either. The nginx configuration does not have any compression options set either.

I believe adding it to `cached.php` with the right headers (content-type **and** compression-type), with storing the compressed file should work. You should be able to test that yourself on your local development environment too.

2024-10-25 02:43 UTC, lwlwilliam commented on js/interactive-examples.js
> +    const phpcode = example.querySelector(".phpcode");
```suggestion
  document.querySelectorAll(".example .example-contents").forEach((example) => {
    const button = document.createElement("button");
    button.setAttribute("type", "button");
    const phpcode = example.querySelector(".phpcode");
    if (phpcode === null) {
      return;
    }
```

There may be multiple `.phpcode` tags under `.example` tag.

![image](https://github.com/user-attachments/assets/094c186d-91c2-4ae4-b2fe-0e119b080cad)

2024-10-28 11:17 UTC, derickr commented
I don't quite understand whether your "try" was succesful or not. I can only see an image.

The javascript should surely be calling `/cached.php?....` and not the `.wasm` file directly...?

And we deploy on nginx, so you should test with that, and not with something else. I have just added the nginx configuration to the systems repository: https://github.com/php/systems/tree/master/php-web4/nginx

2024-10-28 12:10 UTC, shaedrich commented
> @pronskiy added version:

Should there be only one version or all of the supported in a dropdown/select?

2024-10-28 14:29 UTC, pronskiy commented
@shaedrich, for the sake of simplicity of this first step, it's better to stick to just one version. The dropdown sounds like a good idea for the next step.

2024-10-30 22:49 UTC, cookieguru commented
Probably want to add
```gitattributes
js/php-web.wasm filter=lfs diff=lfs merge=lfs binary
```
to `.gitattributes`

2024-11-19 09:47 UTC, pronskiy commented
@derickr, @saundefined, @sy-records, folks, do you think this is ready to merge?

2024-11-19 14:22 UTC, saundefined approved these changes

2024-11-27 11:33 UTC, derickr commented
I am getting failures when I try to check out this branch:

```
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 31 (delta 17), reused 27 (delta 16), pack-reused 0 (from 0)
Unpacking objects: 100% (31/31), 1.20 MiB | 1.79 MiB/s, done.
From https://github.com/php/web-php
 * [new ref]           refs/pull/1097/head -> pr/1097
M	distributions
Switched to branch 'pr/1097'
Encountered 1 file that should have been a pointer, but wasn't:
	js/php-web.wasm
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
```

It is perhaps because something is on LFS, or not? The file just *looked* checked in here, so what is the deal with adding `lfs` to `.gitattributes`?

If it *is* LFS, then you need to provide instructions as to how to check it out properly.

2024-11-27 11:36 UTC, derickr requested changes
I am getting failures when I try to check out this branch:

```
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 31 (delta 17), reused 27 (delta 16), pack-reused 0 (from 0)
Unpacking objects: 100% (31/31), 1.20 MiB | 1.79 MiB/s, done.
From https://github.com/php/web-php
 * [new ref]           refs/pull/1097/head -> pr/1097
M	distributions
Switched to branch 'pr/1097'
Encountered 1 file that should have been a pointer, but wasn't:
	js/php-web.wasm
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
```

It is perhaps because something is on LFS, or not? The file just *looked* checked in here, so what is the deal with adding `lfs` to `.gitattributes`?

If it *is* LFS, then you need to provide instructions as to how to check it out properly.

2024-12-03 10:32 UTC, merged

2024-12-03 10:33 UTC, derickr commented
Merged, thanks so much!

It should be live in the next hour or so.

2024-12-03 12:42 UTC, bohwaz commented
hey guys, the WASM file doesn't appear to be compressed by the server?

2024-12-03 18:25 UTC, soyuka commented
@derickr to what script may I add the `php.wasm` build on https://github.com/php/systems/ ? 

> hey guys, the WASM file doesn't appear to be compressed by the server?

Would https://github.com/php/systems/pull/67 work? IMO we should get rid of `cached.php` and leave assets compression and cache management to nginx (or caddy).

2024-12-03 21:31 UTC, cookieguru commented
I meant to comment on this before it got merged, but removing it from LFS was not the way to go.  Running a git clone/pull now needs to download an additional 3.6 MB for this commit alone, and that will increase every time the wasm file is updated.  By placing it in LFS, only the version tied to the commit would have ever need to be fetched.  I think a simple `git lfs install` would have fixed the original issue

2024-12-04 11:41 UTC, derickr commented
@cookieguru We don't want to use LFS just yet - it's probably better to not have the WASM file in the repo at some point, but that causes problems too for deployment.

2024-12-04 11:43 UTC, derickr commented
Let's continue this discussion in https://github.com/php/systems/pull/67 (only).

2024-12-11 10:30 UTC, saundefined commented
@soyuka @pronskiy @Girgias 

What do you think to add selector with active PHP versions (e.g. 8.1-8.4)?

if the code behavior differs between versions, we display these differences in the documentation,
I think interactive examples would be more illustrative.

I suppose this way we can do away with `&example.outputs.*;` blocks altogether in the future.

2024-12-11 14:32 UTC, pronskiy commented
@saundefined, it totally makes sense to me.
How do you think it would work from a user’s perspective?

For example if the dropdown defaults to PHP 8.4, I hit Run, and it shows the 8.4 output. Then I switch the dropdown to 8.3 and hit Run again. Would it replace the output or show the diff somehow?

2024-12-11 16:39 UTC, Girgias commented
@derickr part of your concern seems to be fixed by: https://github.com/php/web-php/pull/1180

But not all examples produce output, which is a different issue.

2024-12-16 17:33 UTC, shaedrich commented
> @soyuka @pronskiy @Girgias
> 
> What do you think to add selector with active PHP versions (e.g. 8.1-8.4)?

I suggested the same thing:

> > @pronskiy added version:
> 
> Should there be only one version or all of the supported in a dropdown/select?

so, I'd love to have that as well. Maybe, now is the right time to implement it, now that the initial implementation is merged

2024-12-16 21:03 UTC, pronskiy commented
> Having multiple versions also means you need to have users download the wasm binary multiple times. I really don't think we should focus on that. 
@derickr, not necessarily. Any version of Wasm should be downloaded only when the user clicks “Run” for the first time.

For example:
* I visit php.net, and 8.4 is selected by default. No Wasm is loaded initially.
* I press “Run,” and the 8.4 Wasm binary is loaded and cached in the browser.
* I switch to version 8.3 using the dropdown and press “Run.” The 8.3 Wasm binary is then loaded and cached in the browser.
* Now, if I switch between 8.4 and 8.3, the examples run smoothly because the corresponding Wasm binaries are already cached.