allow "/" when editing code
php/web-php pull request #1177
Opened 2024-12-03 18:53 UTC by soyuka

It was reported that you can't hit "/" when editing code, this fixes it. I was suprised that this part of the code doesn't use `mousetrap` as in `js/common.js`.

2024-12-04 01:26 UTC, sy-records commented on js/search.js
> +
Changing it this way will make it impossible to use the `/` popup search input box

2024-12-04 06:59 UTC, sy-records requested changes

2024-12-04 06:59 UTC, sy-records commented on js/search.js
> +        if (event.target.contentEditable) {
```suggestion
        if (event.target.contentEditable === 'true') {
```

2024-12-04 07:13 UTC, sy-records approved these changes

2024-12-04 07:16 UTC, merged

2024-12-05 09:30 UTC, soyuka commented
Thanks @sy-records !