added Web Summer Camp 2025 conference
php/web-php pull request #1196
Opened 2024-12-31 15:11 UTC by ilukac

2024-12-31 15:47 UTC, saundefined requested changes
Thanks!

2024-12-31 15:47 UTC, saundefined commented on archive/entries/2024-12-31-1.xml
> +  <default:finalTeaserDate xmlns="http://php.net/ns/news">6000-12-31</default:finalTeaserDate>
```suggestion
  <default:finalTeaserDate xmlns="http://php.net/ns/news">2025-07-03</default:finalTeaserDate>
```

2024-12-31 15:47 UTC, saundefined commented on archive/entries/2024-12-31-1.xml
> +  <content type="xhtml">
Would you like to place some logo?

```suggestion
  <category term="conferences" label="Conference announcement"/>
  <default:newsImage xmlns="http://php.net/ns/news" link="https://www.websummercamp.com" title="Web Summer Camp 2025">PATH_TO_IMAGE.png</default:newsImage>
  <content type="xhtml">
```

2025-01-08 09:23 UTC, ilukac commented on archive/entries/2024-12-31-1.xml
> +  <default:finalTeaserDate xmlns="http://php.net/ns/news">6000-12-31</default:finalTeaserDate>
Got it, thanks

2025-01-08 09:24 UTC, ilukac commented on archive/entries/2024-12-31-1.xml
> +  <content type="xhtml">
Added!

2025-01-08 10:02 UTC, sy-records approved these changes

2025-01-08 10:02 UTC, sy-records commented on archive/entries/2024-12-31-1.xml
> +  <category term="conferences" label="Conference announcement"/>
LGTM. 


Should it be Call for Papers?

```suggestion
  <category term="cfp" label="Call for Papers"/>
```


<img width="401" alt="image" src="https://github.com/user-attachments/assets/7138c232-98cc-4b41-9c79-4ddde68d7704" />

2025-01-08 13:43 UTC, ilukac commented on archive/entries/2024-12-31-1.xml
> +  <category term="conferences" label="Conference announcement"/>
Well, it could be both, but I would prefer the first

2025-01-08 23:59 UTC, merged