Fix to allow news2html to handle multi-line 'module'
php/web-php pull request #417
Opened 2021-07-21 18:29 UTC by mikeschinkel

I am not sure this PR is valid because I only had one set of NEWS files to process.  But, maybe it is:

I needed a NEWS file to test bin/news2html and the only ones in the repo were /resources/NEWS_5_4_0_*.txt. Unfortunately, those had a few 'entries' that appeared to have no 'modules' and that caused the script to crash. So I added logic to recognize those and assign them to the 'Core' module and that allowed the script to work. As part of this, I unravelled the if..elseif..else logic to be a series of if..continue since the if statements were all in a loop and no code was run after the if..elseif..else statement.

2021-07-21 19:56 UTC, mikeschinkel commented on license/index.php
> +  Starting with PHP 4, versions of the PHP software are distributed under the
This is already in master but evidently I didn't rebase before submitting the PR.

2021-07-21 20:24 UTC, cmb69 commented
You can use the NEWS files in php-src for testing, e.g. https://github.com/php/php-src/blob/master/NEWS and https://github.com/php/php-src/blob/PHP-7.3/NEWS. Older NEWS files are likely irrelevant now,

2021-07-21 20:26 UTC, mikeschinkel commented
@cmb69 — Thanks.

2021-07-21 23:11 UTC, salathe commented
> Are NEWS files hand-coded, or generated from some other source?

The NEWS files are hand-written.

2021-07-21 23:17 UTC, mikeschinkel commented
@salathe — Thanks for answering.  
That is a high bar for getting the form exactly right every time... _(just thinking out loud.)_

2023-08-09 16:53 UTC, sgolemon requested changes

2023-08-09 16:53 UTC, sgolemon commented on bin/news2html
> +			array('<?php bugfix("$1"); ?>', '<?php peclbugfix("$1"); ?>', '<?php implemented("$1"); ?>', '<?php githubissuel(\'php/php-src\',"$1"); ?>'),
Why this change?

1/ Adding quotes violates the type of the agument `"123" == 123` but `"123" !== 123`.
2/ \1 and $1 are effectively the same here, this seems to be change for the sake of change.

2023-08-09 16:53 UTC, sgolemon commented on bin/news2html
> +	if ( !isset($entries[$module])) {
This feels like a very specific fix for 4.x NEWS files.
Would you mind if this were opt-in behavior?
e.g. `bin/news2html --handle-multiline-entry-looks-like-module ...`

Modern NEWS files don't have this issue (you can find them in the php-src repo, every branch has its own NEWS file at the root of the repo), and nominally this script is only run on new releases.

2023-08-09 16:53 UTC, sgolemon commented on bin/news2html
> +	    $entries['Core'][] = $module;
What's with this `Core` module biasing?  My guess is that the bug is only being seen in fixes for the core module, but it seems like it COULD occur in any module.

2023-12-02 01:02 UTC, closed without merging