Add PHP 8.1 release page (WIP)
php/web-php pull request #450
Opened 2021-10-18 13:23 UTC by pronskiy

The release page for PHP 8.0 looked nice and worked well. With the approaching PHP 8.1 release, it would be great to update the page and the menu link.

@krakjoe, @patrickallaert, @ramsey, folks please let me know what you think.

Todo:
- [x] Update the logo 
         _// The logo was updated with permission from Vincent Pontier, the PHP 8 logo author._
- [x] Create content structure for English page
- [ ] Finalize content in English
- [ ] Remove code duplication
- [ ] Create stub files for other languages

2021-11-09 18:01 UTC, kelunik commented on releases/8.1/en.php
> +      <p>Fibers are primitives for implementing light weight cooperative concurrency. Basically they are a means of creating code blocks that can be paused and resumed, much like threads. The main di
```suggestion
      <p>Fibers are primitives for implementing light weight cooperative concurrency. Basically they are a means of creating code blocks that can be paused and resumed, much like threads. The main difference is that they are never preempted and that the scheduling must be done by a common library and not the OS.</p>
```

2021-11-09 20:55 UTC, samdark requested changes

2021-11-09 20:55 UTC, samdark commented on releases/8.1/common.php
> +    \site_header("PHP 8.0.0 Release Announcement", [
```suggestion
    \site_header("PHP 8.1.0 Release Announcement", [
```

2021-11-09 20:55 UTC, samdark commented on releases/8.1/common.php
> +<meta name="twitter:title" content="PHP 8.0 Released" />
```suggestion
<meta name="twitter:title" content="PHP 8.1 Released" />
```

2021-11-09 20:55 UTC, samdark commented on releases/8.1/common.php
> +<meta itemprop="name" content="PHP 8.0 Released" />
```suggestion
<meta itemprop="name" content="PHP 8.1 Released" />
```

2021-11-09 20:55 UTC, samdark commented on releases/8.1/en.php
> +      <p>It is not currently possible to mix intersection and union types together such as <code>A&B|C</code>.</p>
```suggestion
      <p>Use intersection types on any type declarations when you need to require a value to satisfy multiple type constraints at the same time.</p>
      <p>It is not currently possible to mix intersection and union types together such as <code>A&B|C</code>.</p>
```

2021-11-09 20:55 UTC, samdark commented on releases/8.1/en.php
> +      <h2 class="php8-h2 php8-h2_margin-top" id="deprecations_and_bc_breaks">Deprecations and backward compatibility breaks</h2>
This list should be reviewed. I don't really get what's broken by reading it.

2021-11-09 20:55 UTC, samdark commented on releases/8.1/en.php
> +      <a class="php8-button php8-button_light" href="/downloads">Upgrade to PHP 8 now!</a>
```suggestion
      <a class="php8-button php8-button_light" href="/downloads">Upgrade to PHP 8.1 now!</a>
```

2021-11-09 20:55 UTC, samdark commented on releases/8.1/en.php
> +        For source downloads of PHP 8 please visit the <a href="https://www.php.net/downloads">downloads</a> page.
```suggestion
        For source downloads of PHP 8.1 please visit the <a href="https://www.php.net/downloads">downloads</a> page.
```

2021-11-19 09:05 UTC, sgolemon commented on releases/8.1/en.php
> +    <div class="php8-compare__main">
What's going on in these two examples?  Before and after is identical and nothing to do with new in initializers.

2021-11-19 09:05 UTC, sgolemon commented on releases/8.1/en.php
> +function count_and_iterate(CountableIterator $value) {
This isn't actually quite equivalent to the 8.1 version.   The CountableIterator is a discrete interface that objects passed in would have to explicitly implement.  Maybe make the example hint one then manually check the other.  It'd be more accurate AND drive home the value of intersection types.

2021-11-19 09:05 UTC, sgolemon commented on releases/8.1/en.php
> +      <p>Use intersection types шт any type declarations when you need to require a value to satisfy multiple type constraints at the same time instead of a single one.</p>
`шт`  <--- WAT?

2021-11-19 09:05 UTC, sgolemon commented on releases/8.1/en.php
> +<section class="php8-section center php8-section_light">
I assume this will look better once the image exists, but right now the rendering in the browser is all messy.

2021-11-23 09:41 UTC, saundefined commented on releases/8.1/en.php
> +      <h2 class="php8-h2 php8-h2_margin-top" id="deprecations_and_bc_breaks">Deprecations and backward compatibility breaks</h2>
```suggestion
    <div class="php8-column">
      <h2 class="php8-h2" id="deprecations_and_bc_breaks">Deprecations and backward compatibility breaks</h2>
```

2021-11-23 09:41 UTC, saundefined commented on releases/8.1/en.php
> +    <div class="php8-compare">
```suggestion
<section class="php8-section center php8-section_light php8-columns">
    <div class="php8-column">
```

2021-11-23 10:01 UTC, Gemorroj commented on releases/8.1/en.php
> +      <p>Use intersection types шт any type declarations when you need to require a value to satisfy multiple type constraints at the same time instead of a single one.</p>
It's "in" on russian keyboard =)

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/common.php
> +        'zh'    => '简体中文',
Remove translations until they appear =)

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +      <a class="php8-rfc" href="https://wiki.php.net/rfc/enumerations">RFC</a>
```suggestion
      <a class="php8-rfc" href="https://wiki.php.net/rfc/enumerations">RFC</a> <a class="php8-rfc" href="/manual/en/language.enumerations.php">Doc</a>
```

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +      <a class="php8-rfc" href="https://wiki.php.net/rfc/noreturn_type">RFC</a>
```suggestion
      <a class="php8-rfc" href="https://wiki.php.net/rfc/noreturn_type">RFC</a> <a class="php8-rfc" href="/manual/en/language.types.declarations.php#language.types.declarations.never">Doc</a>
```

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +            <li>IMAP: imap resources are IMAP\Connection class objects.</li>
```suggestion
            <li>IMAP: imap resources are <code>IMAP\Connection</code> class objects.</li>
```

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +            <li>FTP Extension: Connection resources are FTP\Connection class objects.</li>
```suggestion
            <li>FTP Extension: Connection resources are <code>FTP\Connection</code> class objects.</li>
```

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +            <li>GD Extension: Font identifiers are GdFont class objects.</li>
```suggestion
            <li>GD Extension: Font identifiers are <code>GdFont</code> class objects.</li>
```

2021-11-23 15:18 UTC, saundefined commented on releases/8.1/en.php
> +            <li>New array_is_list function.</li>
```suggestion
            <li>LDAP: resources migrated to <code>LDAP\Connection</code>, <code>LDAP\Result</code>, and <code>LDAP\ResultEntry</code> objects.</li>
            <li>PostgreSQL: resources migrated to <code>PgSql\Connection</code>, <code>PgSql\Result</code>, and <code>PgSql\Lob</code> objects.</li>
            <li>Pspell: pspell, pspell config resources are <code>PSpell\Dictionary</code>, <code>PSpell\Config</code> class objects.</li>
            <li>New <code>fsync</code> and <code>fdatasync</code> functions.</li>
            <li>New <code>array_is_list</code> function.</li>
```

2021-11-23 16:28 UTC, pronskiy commented on releases/8.1/en.php
> +        private Logger $logger = new NullLogger,
Fixed, thanks

2021-11-23 23:55 UTC, sgolemon commented on releases/8.1/release.inc
> +$response = $httpClient->request('https://example.com/');
This really doesn't show off Fibers at all, just what fibers potentially allow your business logic to simplify down to.  Could we maybe put a little more narrative in the paragraph below explaining why this example doesn't really show the feature as a first-class thing?

2021-11-24 10:39 UTC, pronskiy commented on releases/8.1/release.inc
> +$response = $httpClient->request('https://example.com/');
Makes sense. 
@kelunik could you please help with a better example or rewording the paragraph?

2021-11-24 11:22 UTC, lex111 commented on releases/8.1/languages/ru.php
> +        Список изменений представлен в <a href="https://www.php.net/ChangeLog-8.php#PHP_8_1">ChangeLog</a>.
```suggestion
        Список изменений перечислен на странице <a href="https://www.php.net/ChangeLog-8.php#PHP_8_1">ChangeLog</a>.
```

2021-11-24 11:22 UTC, lex111 commented on releases/8.1/languages/en.php
> +    'performance_results' => 'The result (relative to PHP-8.0):<br />
```suggestion
    'performance_results' => 'The result (relative to PHP 8.0):<br />
```

2021-11-24 17:26 UTC, sgolemon commented on releases/8.1/languages/en.php
> +    'performance_results' => 'The result (relative to PHP-8.0):<br />
Looking at the chart graphic, the parenthetical numbers appear to be relative to 7.4, not to 8.0

2021-11-24 20:35 UTC, kelunik commented on releases/8.1/release.inc
> +$response = $httpClient->request('https://example.com/');
@sgolemon Users aren't expected to directly interact with fibers, so everything boils down to showing how business logic can look like now. But I guess we could use an example that uses concurrency vs. just the boilerplate of a non-concurrent call?

2021-11-24 20:53 UTC, pronskiy commented on releases/8.1/release.inc
> +$response = $httpClient->request('https://example.com/');
I have updated the description. What do you think?

2021-11-24 21:18 UTC, pronskiy commented on releases/8.1/languages/en.php
> +    'performance_results' => 'The result (relative to PHP-8.0):<br />
Thanks, Sara. 
I tried to update numbers to make them relative to 8.0, but I found those numbers in [the benchmark results](https://github.com/kocsismate/php-version-benchmarks/blob/main/docs/results/2021_11_11_09_20_1_aws_arm64_c6g_4xlarge/result.md#symfony-demo-app---25-consecutive-runs-250-requests-sec) are [not correct](https://github.com/kocsismate/php-version-benchmarks/issues/5).

I'd suggest removing the chart until we clarify the benchmark results. 

/cc @kocsismate

2021-11-25 15:39 UTC, pronskiy commented on releases/8.1/languages/en.php
> +    'performance_results' => 'The result (relative to PHP-8.0):<br />
Fixed the chart

2021-11-25 16:09 UTC, nikic commented
Should this get merged ahead of the release to make sure everything works?

2021-11-25 16:14 UTC, saundefined commented
Locally looks good, I think we can merge without updating the nav item, and update it simultaneously with the release 🤔

2021-11-25 16:16 UTC, kelunik commented on releases/8.1/languages/en.php
> +    'fibers_content' => '<p>Fibers are primitives for implementing lightweight cooperative concurrency. They are a means of creating code blocks that can be paused and resumed. Fibers do not provide
```suggestion
    'fibers_content' => '<p>Fibers are primitives for implementing lightweight cooperative concurrency. They are a means of creating code blocks that can be paused and resumed like Generators, but from anywhere in the stack. Fibers themselves don't magically provide concurrency, there still needs to be an event loop. However, they allow blocking and non-blocking implementations to share the same API.</p><p>Fibers allow getting rid of the boilerplate code previously seen with <code>Promise::then()</code> or Generator based coroutines. Libraries will generally build further abstractions around Fibers, so there's no need to interact with them directly.</p>',
```

2021-11-25 16:16 UTC, kelunik commented on releases/8.1/release.inc
> +$response = $httpClient->request('https://example.com/');
@sgolemon @pronskiy I've made another suggestion: https://github.com/php/web-php/pull/450/files#r757017743

2021-11-25 16:47 UTC, nikic approved these changes
Some suggestions, but TBH I think it should just be merged in current form and we can tweak details afterwards.

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'common_header' => 'PHP 8.1 is a major update of the PHP language. enums, readonly properties, first-class callable syntax, fibers, intersection types, performance improvements and more.',
```suggestion
    'common_header' => 'PHP 8.1 is a major update of the PHP language. Enums, readonly properties, first-class callable syntax, fibers, intersection types, performance improvements and more.',
```

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'main_subtitle' => 'PHP 8.1 is a major update of the PHP language.<br class="display-none-md"> It contains many new features and optimizations including enums, readonly&nbsp;properties, first-cla
```suggestion
    'main_subtitle' => 'PHP 8.1 is a major update of the PHP language.<br class="display-none-md"> It contains many new features, including enums, readonly&nbsp;properties, first-class&nbsp;callable&nbsp;syntax, fibers, intersection&nbsp;types, performance improvements and more.',
```
I found the "and optimizations" a bit awkward here, as the following is a list of features and we have "performance improvements" at the end.

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'pure_intersection_types_content' => '<p>Use intersection types on any type declarations when you need to require a value to satisfy multiple type constraints at the same time.</p>
```suggestion
    'pure_intersection_types_content' => '<p>Use intersection types when you need to require a value to satisfy multiple type constraints at the same time.</p>
```
This read a bit awkwardly to me, and don't think it needs to be spelled out.

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'bc_return_types' => 'Return types in PHP built-in class methods and deprecation notices.',
```suggestion
    'bc_return_types' => 'Tentative return types in PHP built-in class methods',
```
The "and deprecation notices" here didn't really make sense to me?

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'bc_finfo_objects' => 'finfo Extension: <code>file_info</code> resource are migrated to existing finfo objects.',
```suggestion
    'bc_finfo_objects' => 'finfo Extension: <code>file_info</code> resources are migrated to existing finfo objects.',
```

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'bc_imap_objects' => 'IMAP: imap resources are <code>IMAP\Connection</code> class objects.',
```suggestion
    'bc_imap_objects' => 'IMAP: imap resources become <code>IMAP\Connection</code> class objects.',
```
Maybe (here and below)? Or following the pattern used below:
```suggestion
    'bc_imap_objects' => 'IMAP: imap resources migrated to <code>IMAP\Connection</code> class objects.',
```

2021-11-25 16:47 UTC, nikic commented on releases/8.1/languages/en.php
> +    'bc_sodium_xchacha20' => 'New Sodium XChaCha20 functions.',
I feel like these don't really belong in the BC section -- sure, there is a break due to new functions, but this is not the main point of these changes...

2021-11-25 17:05 UTC, saundefined commented
@nikic thanks! Updated it.
Is it necessary to remove the link from the header to PHP 8.1 page before merging, or merge it as it is?

2021-11-25 17:06 UTC, nikic commented
@saundefined I'd suggest to merge without the link change first.

2021-11-25 17:11 UTC, salathe commented on releases/8.1/languages/en.php
> +              - 27.0% Symfony Demo speedup',
This does not match what the performance chart says for Symfony Demo app (both translations have the same values):
* PHP 8.1: -22.99%
* PHP 8.1 (JIT): -24.12%
* PHP 8.1 (preloading): -23.42%

2021-11-25 17:13 UTC, salathe commented on include/header.inc
> +          <img src="/images/php8/logo_php8_1.svg" alt="php8" height="22" width="60">
Fix alt text:

```suggestion
          <img src="/images/php8/logo_php8_1.svg" alt="php8.1" height="22" width="60">
```

2021-11-25 17:15 UTC, salathe commented on releases/8.1/release.inc
> +function count_and_iterate(CountableIterator $value) {
Maybe something more like....

```suggestion
function count_and_iterate(Iterator $value) {
    if (!($value instanceof Countable)) {
        throw new TypeError('value must be Countable');
    }

```

2021-11-25 17:17 UTC, saundefined commented on releases/8.1/languages/en.php
> +              - 27.0% Symfony Demo speedup',
I can't tell about the results, need to check with @pronskiy.
I think we can hide this block, for now, thoughts?

2021-11-25 17:17 UTC, salathe commented on include/header.inc
> +          <img src="/images/php8/logo_php8_1.svg" alt="php8" height="22" width="60">
Note: do the above when making this change again in header.inc later. 😄

2021-11-25 17:27 UTC, nikic commented on releases/8.1/languages/en.php
> +              - 27.0% Symfony Demo speedup',
The results in the chart should be the correct ones. They were updated yesterday without updating the text. So I'd modify this to `23.0%` for Symfony Demo, to go with the conservative value.

2021-11-25 17:32 UTC, saundefined commented on releases/8.1/languages/en.php
> +              - 27.0% Symfony Demo speedup',
Done

2021-11-25 17:37 UTC, kocsismate commented on releases/8.1/languages/en.php
> +    'performance_results_wordpress' => '3.5 % WordPress speedup',
```suggestion
    'performance_results_wordpress' => '3.5% WordPress speedup',
```

2021-11-25 17:38 UTC, kocsismate commented on releases/8.1/languages/en.php
> +    'performance_results_wordpress' => '3.5 % WordPress speedup',
Or was the change intentional?

2021-11-25 17:48 UTC, salathe commented on releases/8.1/languages/en.php
> +    'performance_results_wordpress' => '3.5 % WordPress speedup',
Not intentional, copy/paste from older text. Thanks!

2021-11-25 17:52 UTC, salathe commented on releases/8.1/languages/en.php
> +    'bc_sodium_xchacha20' => 'New Sodium XChaCha20 functions.',
Moved these to a separate section in 4b9051a

2021-11-25 17:54 UTC, salathe commented
I'm done with making little changes for now. 😊

2021-11-25 17:59 UTC, saundefined commented
@salathe @nikic So.. am I merging it? Minor changes we'll fix after it (if needed)

2021-11-25 18:03 UTC, salathe commented
> @salathe @nikic So.. am I merging it? Minor changes we'll fix after it (if needed)

Sounds good to me. 👍

2021-11-25 18:05 UTC, merged

2021-11-25 18:17 UTC, saundefined commented
Thanks, everyone!
The page is available by URL: https://www.php.net/releases/8.1/

If everything is ok, I'll publish the link in the top navbar.

2021-11-25 18:30 UTC, cmb69 commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
This should be `PHP ≤8.1`. More occurances below.

2021-11-25 18:37 UTC, nikic commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
Why? This is `<=`, not `<`.

2021-11-25 18:38 UTC, salathe commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
Fixed via 948085cf.  Hopefully I got them all.

2021-11-25 18:42 UTC, nikic commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
Or is the point here that the code would still work on PHP 8.1 as well? While technically correct, I think this makes it more confusing, especially as it's also going to work for PHP > 8.1. I'd either revert this change or change it to something completely generic like "Before" and "After".

2021-11-25 18:44 UTC, nikic commented
The spacing after "This effectively makes it possible to use nested attributes." looks a bit awkward.

2021-11-25 18:45 UTC, salathe commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
Hmpf.  But on that argument, isn't "before" also wrong?  Maybe "previously"?

2021-11-25 18:51 UTC, saundefined commented
> The spacing after "This effectively makes it possible to use nested attributes." looks a bit awkward.

Fixed it on the local machine. Also, add the links to the Documentation for First-class Callable Syntax and Explicit Octal numeral notation. Ready to push it with navbar link.

2021-11-25 19:09 UTC, nikic commented
> > The spacing after "This effectively makes it possible to use nested attributes." looks a bit awkward.
> 
> Fixed it on the local machine. Also, add the links to the Documentation for First-class Callable Syntax and Explicit Octal numeral notation. Ready to push it with navbar link.

Go ahead :)

2021-11-25 22:07 UTC, cmb69 commented on releases/8.1/release.inc
> +                <div class="php8-compare__label">PHP ≤8.0</div>
Oops, my comment was nonsense. But maybe "previously" vs. "now"?