Fix: Remove unused references to a global variable
php/web-php pull request #563
Opened 2022-06-27 18:21 UTC by localheinz

This pull request

- [x] removes unused references to the global variable `$MYSITE`

2022-06-27 18:34 UTC, kamil-tekiela commented
Have you checked for side-effects? The keyword `global` has side-effects. https://3v4l.org/b9kH9 I sincerely doubt that this code relied on side-effects, but it could be wise to verify.

2022-06-27 18:39 UTC, localheinz reviewed
Unless there is some magic related to globals involved that I am unaware of, the global variable `@MYSITE` is not referenced here.

2022-06-27 18:39 UTC, localheinz commented on include/do-download.inc
> -    global $MYSITE;
Variable is not referenced in scope:

https://github.com/php/web-php/blob/8fbbe3bb896b3e93a745f4938dee97fc337a4ecd/include/do-download.inc#L26-L42

2022-06-27 18:39 UTC, localheinz commented on include/layout.inc
> -    global $MYSITE;
Variable is not referenced in scope:

https://github.com/php/web-php/blob/8fbbe3bb896b3e93a745f4938dee97fc337a4ecd/include/layout.inc#L485-L524

2022-06-27 18:39 UTC, localheinz commented on include/layout.inc
> -    global $MYSITE;
Variable is not referenced in scope:

https://github.com/php/web-php/blob/8fbbe3bb896b3e93a745f4938dee97fc337a4ecd/include/layout.inc#L525-L529

2022-06-27 18:44 UTC, kamil-tekiela commented
I know it's not referenced in scope, but it's still a keyword that has a global effect. If the variable is not defined in the global scope it sets its value to `null`. That's why I am saying it has a side-effect. See my example above. If you remove this declaration we could possibly get "undefined variable" errors somewhere else in the code.

2022-06-27 22:48 UTC, dragoonis commented
This code gave me nightmares, lol

Trying to remove it but then has other global side effects.

I'm glad you guys are here trying to sort this stuff out 💙

2022-06-28 11:44 UTC, kamil-tekiela requested changes
Other than the middle one, the rest is good.

2022-06-28 11:44 UTC, kamil-tekiela commented on include/do-download.inc
> -    global $MYSITE;
This one is safe to remove. It's not used between declaration and `exit`.

2022-06-28 11:44 UTC, kamil-tekiela commented on include/layout.inc
> -    global $MYSITE;
This one is used in its current scope and cannot be removed.

2022-06-28 11:44 UTC, kamil-tekiela commented on include/layout.inc
> -    global $MYSITE;
This one is 99.99% safe. It's not used in `footer.inc` and that file is meant to be the last thing that is executed. However, given how convoluted this codebase is, it's still possible that some code relies on this declaration. I'd say we risk removing it either way and fix side effect if it occurs.

2022-06-28 11:49 UTC, cmb69 commented on include/layout.inc
> -    global $MYSITE;
Good catch! I hope you're doing well after having checked this code mess. :)

2022-06-28 12:19 UTC, kamil-tekiela approved these changes
Thanks.

2022-06-28 12:20 UTC, merged

2022-06-28 12:23 UTC, localheinz commented
Thank you, @cmb69 and @kamil-tekiela!